### ISSUE TITLE
one screen gets repeated too many times

### ISSUE THREAD

**Issue by linuxgurugamer** [Sigma88/Sigma-LoadingScreens#10]
On a large GPP install, the same RPM screen is shown most of the time, instead of showing the images in the PluginData folder.

This was happening even without any changes being made to SLS configs

**Comment by Sigma88** [comment]
Is this `RPM` screen one of those distributed within GPP?

There might be an issue where one of the textures fails to load and stops the process early so that only a few textures get added to the pool of loading screens

I will take a look.

**Comment by Sigma88** [comment]
I've just tested this on my pc and I can't reproduce this issue.

could you please try this:

## Test1

On a stock KSP 1.3.1 install, add
- Kopernicus 1.3.1-3 (+ requirement from kopernicus archive)
- GPP 1.6.0.1 + GPP_Textures 4.0.0

run the game and upload here the following files:
- output_log.txt
- mmcachefile


## Test2

On a stock KSP 1.3.1 install, add
- Kopernicus 1.3.1-3 (+ requirement from kopernicus archive)
- GPP 1.6.0.1 + GPP_Textures 4.0.0

open the file `GameData/GPP/LoadingScreens/GPP_LS.cfg`

add the line `debug = true` inside the `Sigma88LoadingScreens` node

run the game and upload here the following files:
- output_log.txt
- mmcachefile


this should allow me to pinpoint what is going wrong

if the issues doesn't appear with a standard GPP install, I'll need you to find which mod is affecting LSM and causing it to break. As far as I'm aware there should be no mods incompatible with LSM.

**Comment by linuxgurugamer** [comment]
Will do so this evening

**Comment by Poodmund** [comment]
@linuxgurugamer I'd check out the folder you use to store your Loading Screen Manager images as it sounds as though you have multiple copies of the same, black screen, screenshot image that RPM creates when you take  a screenshot whilst in IVA view.

**Comment by linuxgurugamer** [comment]
Not that, because the LSM dll  wasn't even in the install.

**Comment by linuxgurugamer** [comment]
FYI, I'm pretty sure that the RPM screen is not part of the GPP install, i looked in the folder and didn't see it.

Since the mod only uses DDS files, it will be pretty easy for me to find out where it comes from.

**Comment by linuxgurugamer** [comment]
My bad.
Actually 2 bads:

I went to my backups to get the exact install I was playing with on Sunday and found the following:
1.  LSM was there
2.  The Screenshots directory had 33 of those bad images there, how and why I have no idea. But, LSM was working properly, it was configured to show what was in the Screenshots directory.

My apologies to you, and @Poodmund , you were correct

**Comment by Sigma88** [comment]
I'm glad we sorted that out
