### ISSUE TITLE
Very tiny suggestion

### ISSUE THREAD

**Issue by linuxgurugamer** [Sigma88/Sigma-LoadingScreens#11]
I don't know if you use this, but figured I'm pass this on:

In all of my mods, I have the AssemblyVersion automatically updated with data from the .version file, every time it gets recompiled.  It's available here:  
https://github.com/linuxgurugamer/KSP-Build-Scripts/blob/master/AssemblyVersion.tt
If you do use this, be sure to read the Instructions.txt, which explain how to use it, there are a couple of steps to set it up, and then you can forget about it.

Then, I'm using something like the following line (which I just added,  you will recognize the name) to get the actual version number into a string, which can then be used for messages, etc:

Version = TheChosenOne.assembly.GetName().Version.ToString();

I'm using the AssemblyVersion.tt in all of my mods for debugging purposes.  Even if you don't use the version string, the AssemblyVersion is written to the log file, and you can tell what version someone has installed.  Has been very useful for me at times, when someone claims to be using the latest version and I was able to see that they weren't.

I'd do a PR for this if you like, but it does need a small change done to the .csproj, and I'd rather not touch that file since it is most likely specific to your system.

Hope this helps

**Comment by Sigma88** [comment]
I already have a system to print out the current version, but it's not linked to the version file because I rather keep those two separate.

btw, if you want to use the solution I gave you for multiple installations of your mod you can't include .version files

otherwise KSP-AVC will display multiple instances of the same mod, one for each .version file

**Comment by linuxgurugamer** [comment]
The .version for LSM will only be included for the regular install, for all other installs, they shouldn't include the .version.

But, other than KSP-AVC displaying multiple instances, nothing bad would happen if they are included.

I found that only having to update a single location for the version made my life simpler.

anyway, was just a suggestion.  Go ahead and close this if you want.
